name: Build Android and iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-build:
    name: Build Android APK/AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android  ./gradlew assembleRelease bundleRelease

      - name: Upload APK & AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            android/app/build/outputs/apk/release/app-release.apk

  ios-build:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS IPA
        run: |
          cd ios
          xcodebuild -workspace YourProject.xcworkspace \
            -scheme YourScheme \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/YourApp.xcarchive archive

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath build/YourApp.xcarchive \
            -exportPath build \
            -exportOptionsPlist exportOptions.plist

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/build/*.ipa
