name: Build Android and iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      platform:
        description: "Choose platform to build (Android / iOS / both)"
        required: true
        default: 'both'
        type: string

jobs:
  android-build:
  - name: Platform Input
    run: echo "Platform selected: ${{ inputs.platform }}"
    name: Build Android APK
    runs-on: ubuntu-latest
    if: inputs.platform == 'Android' || inputs.platform == 'both'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Node.js dependencies
        run: |
          npm install

      - name: Set up Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android 
          ./gradlew assembleRelease bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ReactNativeAndroid-build
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            ##./gradlew assembleDebug

